# Generated by Django 5.2.9 on 2025-12-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='OWLS Store', max_length=255)),
                ('site_description', models.TextField(blank=True, default='Welcome to our store')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('support_email', models.EmailField(default='support@owls.asia', max_length=254)),
                ('support_phone', models.CharField(default='+84 123 456 789', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
